# theme: jekyll-theme-midnight
# remote_theme: riggraz/no-style-please 
remote_theme: broccolini/swiss
theme_color: black
title: Open Battle System
description: Bookmark this to keep an eye on my project updates!
github_username: openbattlesystem
github_repo: openbattlesystem.github.io 
